### PR TITLE
persistent nock caching

### LINKED ISSUE #148: Ares needs persistent caching
Vere will shortly be able to cache data across events using a persistent cache. This is not currently implemented in Ares.

### PR DESCRIPTION
**Pull request by matthew-levan**
Implements UIP-0103 for Ares. See https://github.com/urbit/vere/pull/508 for more. This PR depends on #143 to fix the "double jamming" problem, and also for an interface by which to implement cache reclamation/eviction for the persistent cache (`keep`).

Resolves #148.

### CODE REVIEW

**Comment by eamsden** [comment]
@matthew-levan aside from the PMA what does this need? We discussed eviction strategies, what is done in vere?

**Comment by matthew-levan** [comment]
Schmitt algorithm is implemented, see here:
https://github.com/urbit/vere/pull/549

**Comment by matthew-levan** [comment]
I still need to test this too-- a couple bugs from earlier this week
prevented me from booting and testing when I was writing this.

**Comment by joemfb** [comment]
in vere, the underlying HAMT is also capped, with CLOCK eviction.

**Pull request closed without merging**
